--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
- !ruby/struct:SM::Flow::P 
  body: "@CONF default setting"
full_name: IRB::init_config
is_singleton: true
name: init_config
params: (ap_path)
visibility: public
