--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
- !ruby/struct:SM::Flow::P 
  body: running config
full_name: IRB::run_config
is_singleton: true
name: run_config
params: ()
visibility: public
