--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
- !ruby/struct:SM::Flow::P 
  body: Returns an array containing the elements in <em>self</em> corresponding to the given selector(s). The selectors may be either integer indices or ranges. See also <tt>Array#select</tt>.
- !ruby/struct:SM::Flow::VERB 
  body: "   a = %w{ a b c d e f }\n   a.values_at(1, 3, 5)\n   a.values_at(1, 3, 5, 7)\n   a.values_at(-1, -3, -5, -7)\n   a.values_at(1..3, 2...5)\n"
full_name: Array#values_at
is_singleton: false
name: values_at
params: |
  array.values_at(selector,... )  -> an_array

visibility: public
